[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
cpal = "0.15.3"
dasp = "0.11.0"
dasp_signal = "0.11.0"
hound = "3.5.1"
rand = "0.8.5"

